### ISSUE TITLE
Vorschlag: Anpassung der Software für Tiefschlaf

### ISSUE THREAD

**Issue by Zentris** [lh84/moisture_sensor_esp12#1]
Die ursprüngliche Software ist ausgelegt für den ESP8266-01. Dieser hat aufgrund seiner nur eingeschränkten GPIO-Anzahl nicht die Möglichkeit, auf ein retriggern aus dem Tiefschlaf (timergesteuert) zu erwachen. 

Durch den Einsatz des ESP8266-12(E) könnte die Möglichkeit des Tiefschlafs des ESP genutzt werden, um den Stromverbrauch drastisch zu reduzieren und die Laufzeit/Akkuladung zu erhöhen.

**Comment by lh84** [comment]
Hi @Zentris Danke für den Hinweis. Ich habe nun mein Board soweit fertig und habe deine SOftware V2.2. genutzt. Sie funktioniert echt prima. Danke für deine Arbeit. Ich werde bald mit meinem Board ein paar richtige Tests in Erde machen... Mal sehen wie es läuft und wie lange die 18650 durch hält.
