### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by theopensourcerer** [lh84/moisture_sensor_esp12#4]
Hi again,

I wanted to know what license you want to use for your schematic and PCB design? The reason I ask, is I have re-designed your work in Kicad (my preferred schematic and board design tool) and want to publish in my own repository on Github. I will, obviously, attribute you as the originator but I need to know the license. If you have not chosen a license yet, I have started using the "Solderpad License" for schematics and PCB designs as it seemed rather appropriate (and I know the author):

http://solderpad.org/licenses/SHL-0.51/

It is quite a liberal license based on Apache 2.0.

**Comment by theopensourcerer** [comment]
Would you mind if I use a Creative Commons - Attribution-NonCommercial-ShareAlike? The reason I suggest this is that I am using another idea for the actual probe layout (seems to be very high capacitance BTW - my probe on the bench was recording frequencies in the range of 15kHz - 80kHz with a couple of 100kOhms) and this author used a Creative Commons:

https://github.com/acolomitchi/cap-soil-moisture-v2

**Comment by lh84** [comment]
Hi, 
sorry that I didn't answer. I didn't get any notifications from github. I don't know which license is the best. 

But I would prefer when we bundle all the know How at this repo. What do you think?

**Comment by lh84** [comment]
https://github.com/lh84/moisture_sensor_esp12/blob/master/LICENSE

**Comment by lh84** [comment]
https://github.com/lh84/moisture_sensor_esp12/blob/master/LICENSE
